name: Deploy Infra

on:
  workflow_dispatch:

env:
  resourceGroupName: rg-iac-demo
  storageNamePrefix: techdemo

jobs:
  infra-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
