name: Deploy Infra

on:
  workflow_dispatch:

env:
  resourceGroupName: rg-iac-demo
  storageNamePrefix: techdemo

jobs:
  infra-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: Azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Optional debug step
      - name: List files
        run: ls -R

      # Validate
      - name: Validate Bicep
        uses: Azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ env.resourceGroupName }}
          template: ./infra/templates/deploy_envt.bicep
          parameters: storageNamePrefix=${{ env.storageNamePrefix }}
          deploymentMode: Validate

      # Deploy
      - name: Deploy Bicep
        uses: Azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ env.resourceGroupName }}
          template: ./infra/templates/deploy_envt.bicep
          parameters: storageNamePrefix=${{ env.storageNamePrefix }}
          deploymentMode: Incremental
